### ISSUE TITLE
"return redirect" fully reloads the page

### ISSUE THREAD

**Issue by pasindujr** [tonysm/turbo-laravel#90] opened 2022-09-04 10:23 UTC
I have been developing a Laravel 9 application with Livewire and using Turbo Laravel package for give it a SPA feeling. It works fine with regular links, but there is a register page in my application and after registration is successful, I have given a redirect to the same page. but after I clicked the register button the page does a full reload. How can I fix that? Is this a issue with the package. I have tried different redirect notations but the issue remains.

```php
$user = new User;
        $user->name = $this->name;
        $user->username = $this->username;
        $user->gender = $this->gender;
        $user->user_image_path = $userImageName;
        $user->email = $this->email;
        $user->password = Hash::make($this->password);
        $save = $user->save();

        if ($save) {
            return redirect('/regsiter');
        } else {
            return $this->error = 'Something went wrong! Please try again.';
        }
```

**Comment by pasindujr** [comment] 2022-09-04 11:09
Sorry my bad, I have missed the step where I should install the `Turbo HTTP Middleware` thinking it is optional. This issue is fixed now.

**Comment by stevebrainng** [comment] 2022-09-04 11:44
redirecting to the same page will trigger a full page reload because you are on the same page. try return redirecting to login page to see if it works...

**Comment by pasindujr** [comment] 2022-09-04 11:54
> redirecting to the same page will trigger a full page reload because you are on the same page. try return redirecting to login page to see if it works...

I tried that but did not work.

**Comment by stevebrainng** [comment] 2022-09-04 12:07
Try redirecting to a named route... 
return redirect()->route('register');

**Comment by tonysm** [comment] 2022-09-05 17:30
@pasindujr where is this redirect happening? Is that in a Livewire action? Or a controller action? Can you provide a sample application code where this happens? I'd recommend creating a fresh Laravel app where this error happens and publishing that to GitHub.

**Comment by tonysm** [comment] 2022-09-10 17:42
Closing this for now since I didn't get an answer and doesn't seem like an issue for this package. Feel free to reopen it if you think it is and, pls, try creating a demo app where you're able to reproduce the issue, publish that to GitHub and share with me.

**Closed by tonysm** 2022-09-10 17:42 UTC
